"""Shared validator release/package version constants."""

VALIDATOR_RELEASE_VERSION = "20261006.post0"
VALIDATOR_PACKAGE_VERSION = "20261006.post0"

__all__ = ["VALIDATOR_PACKAGE_VERSION", "VALIDATOR_RELEASE_VERSION"]
