"""Shared validator release/package version constants."""

VALIDATOR_RELEASE_VERSION = "20260728.post8"
VALIDATOR_PACKAGE_VERSION = "20260728.post8"

__all__ = ["VALIDATOR_PACKAGE_VERSION", "VALIDATOR_RELEASE_VERSION"]
